name: ioos-asset-inventory
channels:
  - conda-forge
dependencies:
  - cfunits
  - ckanapi
  - erddapy
  - fiona
  - geopandas
  - geoplot
  - html5lib
  - jupyter
  - lxml
  - matplotlib-base
  - netcdf4
  - openpyxl
  - pandas
  - python=3.14
  - xarray
  - xlrd
